name: Build and Test

# Controls when the workflow will run
on: 
  push:
  
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build and Test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - run: flutter --version
    - run: flutter pub get

    - name: Flutter analyzer
      run: flutter analyze

    - nane: Run Dart Code Metrics
      run: |
        flutter pub global activate dart_code_metrics
        flutter pub global run dart_code_metrics:metrics analyze lib --reporter=json

    - run: flutter test --coverage

    - name: Publish to Codeclimate
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

      #- run: flutter build apk
      #- run: flutter build appbundle
